FROM golang:latest

MAINTAINER Nic Jackson <jackson.nic@gmail.com>

RUN echo y | sudo apt-get install ruby
RUN echo y | sudo apt-get install ruby-dev
RUN echo y | sudo apt-get install build-essential
